### ISSUE TITLE
Encrypted Images.

### ISSUE THREAD

**Issue by salmos23** [jlguardi/yowsup#24]
Hello , I 'm trying to download images and the download is encrypted. Is there any way to download without encryption ? Thank you.

2016-03-30 16:18:02,104 [wa] INFO - Received image /home/ariel2510/www/productos/tmp80jkE2.jpg 
2016-03-30 16:18:02,105 [wa] DEBUG - 
2016-03-30 16:18:02,105 [walistener.wa_layer] DEBUG - [Media Type:image, Size:14418, URL:https://mmi666.whatsapp.net/d/uKDDl78O7Zmi3n2PJYQQU1b8XqU/AlK0PFHVbbQ1b6AH8QuVvqSSSnomRLXVJv43XRLv60v1.enc]

**Comment by jlguardi** [comment]
Update your code!! Current version of cli downloads unencrypted image.

De: salmos23
Enviado: jueves, 31 de marzo de 2016 02:20
Para: jlguardi/yowsup
Responder a: jlguardi/yowsup
Asunto: [jlguardi/yowsup] Encrypted Images. (#24)

Hello , I 'm trying to download images and the download is encrypted. Is there any way to download without encryption ? Thank you.

2016-03-30 16:18:02,104 [wa] INFO - Received image /home/ariel2510/www/productos/tmp80jkE2.jpg
2016-03-30 16:18:02,105 [wa] DEBUG -
2016-03-30 16:18:02,105 [walistener.wa_layer] DEBUG - [Media Type:image, Size:14418, URL:https://mmi666.whatsapp.net/d/uKDDl78O7Zmi3n2PJYQQU1b8XqU/AlK0PFHVbbQ1b6AH8QuVvqSSSnomRLXVJv43XRLv60v1.enc]

---

You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/jlguardi/yowsup/issues/24

**Comment by salmos23** [comment]
@jlguardi I am so sorry but I updated and url is still coming encrypted. I tested in both Env (S40 and Android ).

Downloading https://mmi301.whatsapp.net/d/ayp5H6HVGII0-bpwFV9g0lb8i0s/AhoYSGRyOBxU_e10rVOLf2YR71tuQdOOKyP-bFcVh4v1.enc

**Comment by jlguardi** [comment]
Obviously url content is encoded. Cli prints the local path where unencrypted media is saved.

**Comment by salmos23** [comment]
I understand but I still receive the image in my path encrypted. Received image /home/ariel2510/www/productos/tmpSerdkt.jpg  (This jpg is encrypted).

**Comment by jlguardi** [comment]
Please, post logs. It ins't a path/name used by cli. It's easy, update you code, make sure to install it and older versions are removed, run cli with -d flag and send and image from oficial android.
If cli log doesn't show "URL:https://....enc FILE:/tmp/...jpg", you've made something wrong. Retry step by step. 
So, if FILE content is encrypted, post logs.

**Comment by bdbais** [comment]
I'm using my script, not cli based, how can I download not-encrypted images?

**Comment by jlguardi** [comment]
Read cli. It's just a line like:

```
 def onMedia(self,message):
    with open('filename','wb') as f:
       f.write(message.getMediaContent())
```

Check before the type of media (url,location don't work like that.

And read cli code!!!
