### ISSUE TITLE
what needs to be changed from tgalal version to this version

### ISSUE THREAD

**Issue by Marcovus** [jlguardi/yowsup#38]
because of the issue with xml not well formed I´d like to try this version to see if it will work: https://github.com/tgalal/yowsup/issues/856

I´m just wondering what needs to be changed in the layer and in the init file to get it working with this version. I tried to discored the samples but for example don´t find the method to send the messages. 

in my old file I used this method:
    def sendMsg(self, msg, num):
        outgoingMessage = TextMessageProtocolEntity(content.encode("utf-8") if sys.version_info >= (3,0) else content, to = self.aliasToJid(number))
        logger.info("Sending Message {0} to {1}".format(msg, num))
        self.toLower(outgoingMessage)

does not seem to work anymore

Also sending ACK seems to be diffrent now, because I receive: 
2016-04-02 12:15:58,096 WARNING  whatsapp      -- layer.py:handleEncMessage:257
2016-04-02 12:15:58,100 WARNING  whatsapp     Too many retries!! Going to send the delivery receipt myself! -- layer.py:handleEncMessage:260
2016-04-02 12:15:58,115 DEBUG    whatsapp     tx:
<receipt id="18CB74F7C40FA4ED62" to="491608023444@s.whatsapp.net" t="1459592157">
</receipt>
 -- layer.py:send:8

[old_files.zip](https://github.com/jlguardi/yowsup/files/200777/old_files.zip)

**Comment by freelo** [comment]
You are looking for the difference between two repositories? Just pull both and start your favourite diff tool. And please note that the difference may change daily, so keep pulling/diffing. :)

**Comment by jlguardi** [comment]
@Marcovus Some comments:
In your code:

```
def sendMsg(self, msg, num):
outgoingMessage = TextMessageProtocolEntity(content.encode("utf-8") if sys.version_info >= (3,0) else content, to = self.aliasToJid(number))
logger.info("Sending Message {0} to {1}".format(msg, num))
self.toLower(outgoingMessage)
```

You have mixed msg, num variables with content and number. Moreover, you are applying "format" with str and unicode, use in logger.info unicode. These are bugs of your code. Fix it with:

```
def sendMsg(self, msg, num):
outgoingMessage = TextMessageProtocolEntity(msg.encode("utf-8") if sys.version_info >= (3,0) else content, to = self.aliasToJid(num))
logger.info(u"Sending Message {0} to {1}".format(msg, num)) #### <--- See the u
self.toLower(outgoingMessage)
```
- You are getting encryption error in incoming messages. Send a message to the recipint from yowsup-cli or from your app and it will be fixed. And remember: DO NOT DELETE ENCRYPTION DATABASE or you will get this error again.

In order to compare both codes, download and use diff, meld... or just configure git and use git diff (you can find many solutions googling).
