### ISSUE TITLE
Receiving message cause retry 4 times

### ISSUE THREAD

**Issue by bdbais** [jlguardi/yowsup#40]
I'm using my own script based on EchoLayer example with sending message and after last upgrade I resolved problem with encryption media (very thank you) but I found another problem with receiving message and sending messages:

WARNING:axolotl.sessionbuilder:We've already setup a session for this V3 message, letting bundled message fall through...

WARNING:yowsup.layers.axolotl.layer:'ascii' codec can't decode byte 0xe2 in position 110: ordinal not in range(128)

WARNING:axolotl.sessionbuilder:We've already setup a session for this V3 message, letting bundled message fall through...
WARNING:yowsup.layers.axolotl.layer:'ascii' codec can't decode byte 0xe2 in position 110: ordinal not in range(128)

WARNING:axolotl.sessionbuilder:We've already setup a session for this V3 message, letting bundled message fall through...
WARNING:yowsup.layers.axolotl.layer:'ascii' codec can't decode byte 0xe2 in position 110: ordinal not in range(128)

WARNING:axolotl.sessionbuilder:We've already setup a session for this V3 message, letting bundled message fall through...
WARNING:yowsup.layers.axolotl.layer:'ascii' codec can't decode byte 0xe2 in position 110: ordinal not in range(128)

WARNING:yowsup.layers.axolotl.layer:'ascii' codec can't decode byte 0xe2 in position 110: ordinal not in range(128)
WARNING:yowsup.layers.axolotl.layer:Too many retries!! Going to send the delivery receipt myself!

and It didn't send a reply back.

I think it's a decoding problem, tried to send back a string message and it works, but when I take a text from db this error appear.

**Comment by freelo** [comment]
I think this is a general problem of the current axolotl layer, which catches any exception that occurs even in the user's own code. It is quite likely that your mentioned decode error originates from your own code, but the exception is caught and printed by the axolotl layer.

@jlguardi This seems to be a trap I ran into yesterday as well. Instead of honouring an exception in my reception code, axolotl simply retried and finally sent a receipt. That generic Exception catching was introduced in 0031df4c, see line 256. I don't think an otherwise transparent axolotl layer should be doing such stuff. Yes, it does emit a warning concerning the actual error(without stack trace), but I rather want the exception to be seen in higher levels (a crashing application is better than a suppressed/conceiled error).

**Comment by jlguardi** [comment]
@freelo Of course. But I got an axolotl genric Exception and I was trying to deal with:
yowsup/layers/axolotl/store/sqlite/liteprekeystore.py +20 -> raise Exception("No such prekeyRecord!")

At this moment, I'm getting this kind of errors and I can't avoid them. Just sending a message to the recipient.

**Comment by timoort** [comment]
@jlguardi I am looking for support regarding yowsup. I was wondering if you are interested in helping us. Please contact me via timoor@userlike.com

**Comment by jlguardi** [comment]
@bdbais 
Are you using last master? on this version we have some coder improvements probably related with this error.
@freelo 
I'm fixing it. By now, send a message to recipient  and encryption will work again.

Do not delete axolotl.db or the error will come back.
