### ISSUE TITLE
Audio from groups OK, but not other media types.

### ISSUE THREAD

**Issue by pronetbr** [jlguardi/yowsup#90]
Hello, for some reason, audio coming from groups is received without a problem and acknowledged. But, other media types like image or video are not and I get a "invalid signature" error.

This only happens on groups, and everything is okay on private.

On tgalal master, image messages are received from groups without any issue (although they are encrypted).

Anyone have any idea how to solve this?

Thank you!

**Comment by pronetbr** [comment]
I thought maybe yowsup wasn't getting the correct keys from the group, but this can't be since I can see text messages and audio.

**Comment by jlguardi** [comment]
When I was developing media in groups, I experienced a lot of troubles with key changes (due to changes in participant list). Moreover I got banned my two lines the last time I worked on groups (2 months ago) which is a feature that I don't use. However, I'm quite sure about that all kind of media encryption/decryption worked. If not, the difference is due to a constant used for images, audio and video encryption. You could try to get the url of encrypted video and decrypt it changing the constant up to correct reception.

**Comment by pronetbr** [comment]
Thank you, Jlguardi! I'll investigate this.

**Comment by pronetbr** [comment]
I mixed some of your code with tgalal's master and it's all good now.

For instance, I've borrowed your getMediaContent and a few things from your AxolotlReceivelayer and your protocol_media to make it work all together.

Thanks, mate!

**Comment by jlguardi** [comment]
@pronetbr Please, make a PR on tgalal/master to try t fix this topic.
